name: Instagram Monitor

on:
  schedule:
    # Runs at 00:00 UTC every day (change this time if you want)
    - cron: '0 0 * * *'
  # Also allows you to manually trigger it from the "Actions" tab
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install instawebhooks
          pip install requests

      - name: Run Instagram Monitor
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python instascrape.py
